### ISSUE TITLE
How to employ ChatGPT as the evaluator in Section 3.3?

### ISSUE THREAD

**Issue by LITONG99** [alibaba/GraphTranslator#10]
Dear authors, could you provide the template to employ ChatGPT as the evaluator to perform quantitative analysis? 

According to the paper, the model is input with question-answering pairs of each test sample and uses the four-level (A, B, C, D) rating system. I am wondering what information is provided to the evaluator to make the judgment. For example, does it include the original text, neighborhood information, or the trained prompt? 

Thank you.

**Comment by fs302** [comment]
The evaluation prompt follows the reference paper`Self-instruct: Aligning language model with self generated instructions.`. We provide user and neighbors information as background text, then ask ChatGPT to rate 3 question-answer pairs.
