### ISSUE TITLE
Producer模块的三种信息

### ISSUE THREAD

**Issue by forclh** [alibaba/GraphTranslator#14]
![image](https://github.com/alibaba/GraphTranslator/assets/57589391/225a463f-a9e7-4ba3-947d-507d29c9c983)
请问第三种信息，在代码中是如何体现的

**Comment by smw1996** [comment]
简而言，共性信息主要是由LLM直接总结提取，即是罗列自身节点和邻居节点的信息后，让LLM总结他们的共同特性。如在arxiv数据集中，prompt输入dst_prompt = "\n Please summarize the topic and content of these papers. All answers are in English and No Chinese in your answer"，而针对电商任务，也是类似去总结用户的共同特性。
这点可以参考我们的代码里：
 [ src_prompt = '\n please summarize this paper and list five key words of this paper. All answers are in English and No Chinese in your answer'](https://github.com/alibaba/GraphTranslator/blob/250ff3f41ad5fc1dcf460af4de7c6c6cda72e250/Producer/inference/producer.py#L93)
