### ISSUE TITLE
Question about F1/Recall calculation

### ISSUE THREAD

**Issue by W-rudder** [alibaba/GraphTranslator#2]
Great job! How would F1 and recall metrics be calculated if there are invalid responses? Will the samples with invalid predictions be filtered out?

**Comment by W-rudder** [comment]
For example, in the Taobao (Lifestage) dataset, if the Legality Rate of LLM+s_v is 50.1%, does the F1 calculation for this model only consider the 50.1% of samples with legal responses?

**Comment by fs302** [comment]
@W-rudder Thanks for your question! F1-score is only calculated for the legal responses.
