### ISSUE TITLE
The paper is logically rigorous,but I noticed that in the data obgn-arviv, the document titleabs.tsv cannot be seen, and I also couldn't find the chatglm2-6b file under the models directory. I would appreciate it if you could provide me with some information regarding this.

### ISSUE THREAD

**Issue by lingxiang6** [alibaba/GraphTranslator#3]

**Comment by fs302** [comment]
@lingxiang6 Please refer to the project's `README.md` and download extend data and model.

https://github.com/alibaba/GraphTranslator?tab=readme-ov-file#datasets--models

**Comment by lingxiang6** [comment]
thank you!I found it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shen ***@***.***&gt;; 
发送时间: 2024年4月7日(星期天) 上午10:24
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/GraphTranslator] The paper is logically rigorous,but I noticed that in the data obgn-arviv, the document titleabs.tsv cannot be seen, and I also couldn&#39;t find the chatglm2-6b file under the models directory. I would appreciate it if you could provide me with some information regarding this. (Issue #3)














 
@lingxiang6 Please refer to the project's README.md and download extend data and model.
 
https://github.com/alibaba/GraphTranslator?tab=readme-ov-file#datasets--models
