### ISSUE TITLE
graphsage的预训练问题

### ISSUE THREAD

**Issue by CHAOJICHENG5** [alibaba/GraphTranslator#7]
您好，非常具有启发性的工作！
我有个问题想请教一下，当我想使用GraphSAGE.py文件生成graphsage_node_embeddings.pt时，需要预先加载bert_node_embeddings.pt这个节点嵌入，请问bert_node_embeddings.pt这个模型是如何得到的？

**Comment by guyuisland** [comment]
bert_node_embeddings.pt保存的是每个节点原始的embedding，它是将节点的文本（例如论文的标题和摘要）输入Bert得到的embedding
