### ISSUE TITLE
Sample of Translator output

### ISSUE THREAD

**Issue by NameSpaceQAQ** [alibaba/GraphTranslator#8]
您好，非常感谢您这个有卓越贡献的开源工作！
在阅读论文时，我很想知道Translator的输出样例是什么样的，但是在论文和开源项目中没有看到。
考虑到我这边的设备限制，不太方便部署项目运行来获取这个中间结果，请问您是否能给我提供一个简单的输出样例以供参考？
如能提供，不胜感激，谢谢！

**Comment by guyuisland** [comment]
**这边给一个arxiv数据集的输出，我们的目标是让LLM去预测某篇论文的类别：**
**Title:** ['continual learning using world models for pseudo rehearsal']
**Output：**Based on the summary provided, the paper is most likely to fall under the following 40 arXiv CS sub-categories:

1. Artificial Intelligence: This category includes sub-categories such as machine learning, deep learning, and natural language processing. The paper presents an approach for analyzing user behavior using machine learning algorithms, which falls under the sub-category of "Machine Learning Algorithms."
2. Computer Science and Game Theory: This category includes sub-categories such as computer networks, computer graphics, and computer vision. The paper presents an approach for analyzing user behavior across multiple platforms, which involves the use of computer networks and web analytics tools.
3. Neural and Evolutionary Computing: This category includes sub-categories such as neural networks and evolutionary algorithms. The paper presents an approach for predicting future actions from individual users based on patterns identified through collaborative filtering techniques, which involves the use of neural networks.
4. Robotics: This category includes sub-categories such as robotics and automation. The paper presents an approach for analyzing user behavior across multiple platforms, which involves the use of robots.
5. Social and Information Networks: This category includes sub-categories such as social networks and information networks. The paper presents an approach for analyzing user behavior across multiple platforms, which involves the use of social media data.

**Comment by NameSpaceQAQ** [comment]
感谢您的及时回复！您给出了LLM的预测结果。
不过我想知道的是下图中标出的Translator的输出embedding（作为LLM的输入），如能提供，不胜感激！
![1](https://github.com/alibaba/GraphTranslator/assets/121782221/5df23d58-023d-49da-95c8-8e1422ce3036)

**Comment by guyuisland** [comment]
你好，这个输出的是embedding

**Comment by NameSpaceQAQ** [comment]
好的，谢谢！

**Comment by XY-WHU** [comment]
请问一下这个embbedding是怎么获取到的？arxiv_test.csv文件里的emb是怎么获取到的？
